FizzBuzzSolution/FizzBuzzApplication/Models/FizzBuzzModel.cs
// ---------------------------------------------------------------------------
// <copyright file="FizzBuzzModel.cs" company="TCS">
//     Copyright (c) TCS.  All rights reserved.
// </copyright>
// <summary>
//        File which contains the validations for the User Input.
// </summary>
// ---------------------------------------------------------------------------

namespace FizzBuzzApplication.Models
{
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    /// <summary>
    /// Class which holds user input and stores FizzBuzzList.
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets or sets User input number.
        /// </summary>
        [Required(ErrorMessage = @"*Please enter {0}")]
        [Range(typeof(int), "1", "1000", ErrorMessage = @"Please enter {0} between {1} and {2}")]
        public int? Input { get; set; }

        /// <summary>
        /// Gets or sets FizzBuzzList.
        /// </summary>
        public IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzzSolution/FizzBuzzApplication/Controllers/FizzBuzzController.cs
// ---------------------------------------------------------------------------
// <copyright file="FizzBuzzController.cs" company="TCS">
//     Copyright (c) TCS.  All rights reserved.
// </copyright>
// <summary>
//        File which contains FizzBuzzController class.
// </summary>
// ---------------------------------------------------------------------------
namespace FizzBuzzApplication.Controllers
{
    using System;
    using System.Configuration;
    using System.Web.Mvc;
    using BusinessLayer;
    using Models;
    using PagedList;

    /// <summary>
    /// FizzBuzzController for generating fizz buzz sequence
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// private BusinessLayer interface
        /// </summary>
        private readonly IBusinessLayer businessLayer;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class
        /// </summary>
        /// <param name="ibusinessLayer">businessLayer object</param>
        public FizzBuzzController(IBusinessLayer ibusinessLayer)
        {
            this.businessLayer = ibusinessLayer;
        }

        /// <summary>
        /// Gets page size
        /// </summary>
        private int PageSize
        {
            get
            {
                var pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]);
                if (pageSize <= 0)
                {
                    pageSize = 20;
                }

                return pageSize;
            }
        }

        /// <summary>
        /// Gets or sets input value
        /// </summary>
        private int Input
        {
            get { return Convert.ToInt32(this.TempData["Input"]); }
            set { this.TempData["Input"] = value; }
        }

        /// <summary>
        /// used to return the FizzBuzz Home page
        /// </summary>
        /// <param name="pageNumber">page Number</param>
        /// <returns>FizzBuzzHome View</returns>
        [HttpGet]
        public ActionResult FizzBuzzHome(int? pageNumber)
        {
            FizzBuzzModel model = new FizzBuzzModel();
            if (ModelState.IsValid)
            {
                if (this.Input > 0)
                {
                    model = this.FetchFizzBuzzSequence(this.Input, pageNumber);
                }
            }

            return this.View("FizzBuzzHome", model);
        }

        /// <summary>
        /// used to return the generated FizzBuzz sequence to view
        /// </summary>
        /// <param name="model">FizzBuzzModel Model</param>
        /// <param name="pageNumber">Page Number</param>
        /// <returns>FizzBuzzHome View</returns>
        [HttpPost]
        public ActionResult FizzBuzzHome(FizzBuzzModel model, int? pageNumber)
        {
            if (ModelState.IsValid)
            {
                model = this.FetchFizzBuzzSequence(model.Input.Value, pageNumber);
                ModelState.Clear();
            }

            return this.View("FizzBuzzHome", model);
        }

        /// <summary>
        /// method to call BusinessLayer
        /// </summary>
        /// <param name="inputNumber">input number</param>
        /// <param name="pageNumber">page number</param>
        /// <returns>FizzBuzz Model</returns>
        private FizzBuzzModel FetchFizzBuzzSequence(int? inputNumber, int? pageNumber)
        {
            var fizzBuzzList = this.businessLayer.GenerateFizzBuzzSequence(inputNumber.Value);
            var pagenumber = pageNumber ?? 1;
            this.Input = inputNumber.Value;
            var model = new FizzBuzzModel { Input = inputNumber.Value, FizzBuzzList = fizzBuzzList.ToPagedList(pagenumber, this.PageSize) };
            return model;
        }
    }
}

FizzBuzzSolution/FizzBuzzApplication/Views/FizzBuzz/FizzBuzzHome.cshtml
@model FizzBuzzApplication.Models.FizzBuzzModel
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "FizzBuzzHome";
}
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Fizz.css" rel="stylesheet" type="text/css" />
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("FizzBuzzHome", "FizzBuzz"))
{
    @Html.ValidationSummary(true)
    <div style="border-bottom: 1px solid #bbb">
        <h1>Fizz Buzz Sequence</h1>
    </div> 
    
    <table style="border: 0px; width: 1000px; margin: 10px;">
        <tr>
            <td>
                @Html.LabelFor(model => model.Input, "Enter Input (Ranging 1-1000): ")
                @Html.TextBox("Input", Model.Input)
                @Html.ValidationMessageFor(model => model.Input)

            </td>
        </tr>
        <tr>
            <td style="vertical-align: bottom;">
                <input type="submit" value="Display Fizz Buzz" />
            </td>
        </tr>
    </table>
}

@if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
{
    <table class="table" style="width: 1000px; margin: 10px;">

        @foreach (var sequence in Model.FizzBuzzList)
        {
            <tr>
                <td>
                    @if (sequence.Split(' ').Count() >= 2)
                    {
                        <span class="@sequence.Split(' ')[0]">@sequence.Split(' ')[0]</span>
                        <span class="@sequence.Split(' ')[1]">@sequence.Split(' ')[1]</span>
                    }
                    else
                    {
                        <span class="@sequence">@sequence</span>
                    }
                </td>
            </tr>
        }
    </table>
    @Html.PagedListPager((IPagedList<string>)Model.FizzBuzzList, pageNumber => Url.Action("FizzBuzzHome", new { pageNumber }),
        new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, LinkToFirstPageFormat = String.Format("<<"), LinkToPreviousPageFormat = String.Format("Previous"), LinkToNextPageFormat = String.Format("Next"), LinkToLastPageFormat = String.Format(">>"),MaximumPageNumbersToDisplay=5 })
}